ALTER TABLE `sys_user`
    ADD COLUMN `pin_hash` VARCHAR(100) NULL DEFAULT NULL COMMENT '轻量登录PIN的BCrypt哈希' AFTER `display_name`;

CREATE INDEX `idx_sys_user_active_display_name`
    ON `sys_user` (`status`, `display_name`, `id`);

CREATE TABLE `SPRING_SESSION` (
    `PRIMARY_ID` CHAR(36) NOT NULL,
    `SESSION_ID` CHAR(36) NOT NULL,
    `CREATION_TIME` BIGINT NOT NULL,
    `LAST_ACCESS_TIME` BIGINT NOT NULL,
    `MAX_INACTIVE_INTERVAL` INT NOT NULL,
    `EXPIRY_TIME` BIGINT NOT NULL,
    `PRINCIPAL_NAME` VARCHAR(100) NULL DEFAULT NULL,
    CONSTRAINT `PK_SPRING_SESSION` PRIMARY KEY (`PRIMARY_ID`),
    CONSTRAINT `UK_SPRING_SESSION_ID` UNIQUE (`SESSION_ID`),
    KEY `IX_SPRING_SESSION_EXPIRY_TIME` (`EXPIRY_TIME`),
    KEY `IX_SPRING_SESSION_PRINCIPAL_NAME` (`PRINCIPAL_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Spring Session JDBC会话主表';

CREATE TABLE `SPRING_SESSION_ATTRIBUTES` (
    `SESSION_PRIMARY_ID` CHAR(36) NOT NULL,
    `ATTRIBUTE_NAME` VARCHAR(200) NOT NULL,
    `ATTRIBUTE_BYTES` BLOB NOT NULL,
    CONSTRAINT `PK_SPRING_SESSION_ATTRIBUTES` PRIMARY KEY (`SESSION_PRIMARY_ID`, `ATTRIBUTE_NAME`),
    CONSTRAINT `FK_SPRING_SESSION_ATTRIBUTES` FOREIGN KEY (`SESSION_PRIMARY_ID`)
        REFERENCES `SPRING_SESSION` (`PRIMARY_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Spring Session JDBC会话属性表';
